name: CI/CD for Flask DevOps App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests pytest

      - name: Run Flask in background
        run: |
          nohup python app.py &
          sleep 5

      - name: Run pytest
        run: |
          pytest

      - name: Test /health endpoint
        run: |
          python -c "import requests; response = requests.get('http://127.0.0.1:5001/health'); assert response.status_code == 200"

      - name: Build Docker image
        run: |
          docker build -t devops-flask-app .
